(() => {
  const $ = id => document.getElementById(id), M = window.CalculatorMath;
  const formatMoney = v => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
  const formatPercent = v => new Intl.NumberFormat('pt-BR',{style:'percent',minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
  const parseMoney = value => { const text=String(value).trim(); return text ? Number(text.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'')) : NaN; };
  const inputs = ['initial','contribution','rate','rate-period','term','term-period'];
  function values(){ const rate=$('rate').value,term=$('term').value;return {initial:parseMoney($('initial').value),contribution:parseMoney($('contribution').value),rate:rate===''?NaN:Number(rate)/100,ratePeriod:$('rate-period').value,term:term===''?NaN:Number(term),termPeriod:$('term-period').value}; }
  function formatInput(e){ const raw=parseMoney(e.target.value); e.target.value=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(raw); }
  function updateEquivalence(v){ const rate = v.ratePeriod==='year' ? M.annualToMonthly(v.rate) : M.monthlyToAnnual(v.rate); $('equivalence').textContent = v.rate ? `Taxa equivalente: ${formatPercent(rate)} ${v.ratePeriod==='year'?'ao mês':'ao ano'}.` : ''; }
  function renderTable(rows){ $('evolution-table').innerHTML=rows.map(r=>`<tr><td>Mês ${r.month}</td><td>${formatMoney(r.contribution)}</td><td>${formatMoney(r.invested)}</td><td>${formatMoney(r.periodEarnings)}</td><td>${formatMoney(r.earnings)}</td><td><b>${formatMoney(r.balance)}</b></td></tr>`).join(''); }
  function chart(rows){ const canvas=$('chart'), box=canvas.parentElement.getBoundingClientRect(), dpr=devicePixelRatio||1, w=Math.max(320,box.width),h=310; canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.height=h+'px'; const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h); const pad={l:12,r:12,t:20,b:33}, max=Math.max(...rows.map(x=>x.balance),1), toX=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(rows.length-1,1),toY=v=>h-pad.b-v/max*(h-pad.t-pad.b); c.strokeStyle='#eadfdf';c.lineWidth=1;for(let i=0;i<4;i++){let y=pad.t+i*(h-pad.t-pad.b)/3;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();} function area(key,fill,stroke){c.beginPath();rows.forEach((r,i)=>i?c.lineTo(toX(i),toY(r[key])):c.moveTo(toX(i),toY(r[key])));c.lineTo(toX(rows.length-1),h-pad.b);c.lineTo(toX(0),h-pad.b);c.closePath();c.fillStyle=fill;c.fill();c.beginPath();rows.forEach((r,i)=>i?c.lineTo(toX(i),toY(r[key])):c.moveTo(toX(i),toY(r[key])));c.strokeStyle=stroke;c.lineWidth=2.5;c.stroke();} area('invested','rgba(182,151,154,.18)','#b6979a');area('balance','rgba(197,31,50,.16)','#c51f32'); c.fillStyle='#6f6465';c.font='12px system-ui'; const ticks=[0,Math.floor(rows.length/2),rows.length-1];ticks.forEach(i=>c.fillText(i===0?'Início':`Mês ${rows[i].month}`,toX(i)-10,h-10)); }
  function render(){ const v=values(); try{const r=M.calculate(v);$('form-message').textContent=''; updateEquivalence(v);$('final-value').textContent=formatMoney(r.final);$('final-detail').textContent=`em ${r.months} ${r.months===1?'mês':'meses'}`;$('invested-value').textContent=formatMoney(r.invested);$('earnings-value').textContent=formatMoney(r.earnings);$('return-value').textContent=formatPercent(r.returnRate);$('summary').textContent=`Projeção para ${r.months} meses, com aportes ao final de cada mês.`; $('withdraw-value').textContent=formatMoney(r.final*(Number($('withdraw-rate').value)||0)/100/12);renderTable(r.evolution);chart(r.evolution);}catch(e){$('form-message').textContent=e.message;} }
  $('calculator-form').addEventListener('submit',e=>{e.preventDefault();render();});$('clear').addEventListener('click',()=>{$('initial').value='0,00';$('contribution').value='0,00';$('rate').value='';$('term').value='';render();});['initial','contribution'].forEach(id=>$(id).addEventListener('blur',formatInput));inputs.forEach(id=>$(id).addEventListener('change',render));$('withdraw-rate').addEventListener('input',render);window.addEventListener('resize',()=>{try{chart(M.calculate(values()).evolution)}catch{}});$('year').textContent=new Date().getFullYear();render();
})();
